@startuml Diagram de Clases
class User {
    - username: str
    - email: str
    - password: str
}

class UserData{
    - name: str
    - surname: str
    - phone: str
    - address: str
    - city: str
    - country: str
}

class Role {
    - name: str
    - description: str
}
User "1" *--- "1" UserData : contiene
User "m" o--o "n" Role
@enduml